name: Deploy to Oracle Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H 150.230.251.87 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ubuntu@150.230.251.87 '
            cd ~/CUKLLteam3 || exit 1
            git pull origin main || exit 1
            ./gradlew build || exit 1
            docker build -t spring-app . || exit 1
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d -p 8080:8080 --name spring-app spring-app || exit 1
          '
