name: Deploy to Oracle Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add GitHub and server to known_hosts
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          ssh-keyscan -H 150.230.251.87 >> ~/.ssh/known_hosts

      - name: Deploy to Oracle Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@150.230.251.87 '
            mkdir -p ~/.ssh
            echo "${{ secrets.HOST_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            rm -rf ~/CUKLLteam3/Backend || true
            git clone git@github.com:CUKLLteam3/Backend.git ~/CUKLLteam3/Backend || exit 1
            cd ~/CUKLLteam3/Backend || exit 1
            ./gradlew build || exit 1
            docker build -t spring-app . || exit 1
            docker stop spring-app || true
            docker rm spring-app || true
            docker run -d -p 8080:8080 --name spring-app spring-app || exit 1
          '
